version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuaca-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"  # Nginx berjalan di port 80 di dalam container
    networks:
      - laravel

networks:
  laravel:
